package defaults

func init() {
	register("joy", "joy.png", "smileys")
	register("sob", "sob.png", "smileys")
	register("rage", "rage.png", "smileys")
	register("sunglasses", "sunglasses.png", "smileys")
	register("smirk", "smirk.png", "smileys")
	register("thinking", "thinking.png", "smileys")
	register("upside_down", "upside_down.png", "smileys")
	register("sleeping", "sleeping.png", "smileys")
	register("hot", "hot.png", "smileys")
	register("cold", "cold.png", "smileys")
	register("sick", "sick.png", "smileys")
	register("mind_blown", "mind_blown.png", "smileys")
	register("zipper_mouth", "zipper_mouth.png", "smileys")
	register("money_face", "money_face.png", "smileys")
	register("nauseated", "nauseated.png", "smileys")
	register("puke", "puke.png", "smileys")
	register("yawn", "yawn.png", "smileys")
	register("cry", "cry.png", "smileys")
	register("melting", "melting.png", "smileys")
	register("star_struck", "star_struck.png", "smileys")
	register("heart_eyes", "heart_eyes.png", "smileys")
	register("smiling_devil", "smiling_devil.png", "smileys")
	register("shush", "shush.png", "smileys")
	register("nerd", "nerd.png", "smileys")
	register("chefkiss", "chefkiss.png", "smileys")
	register("skull", "skull.png", "smileys")
}