package permissions

var (
	PermSendMessages         = Register("send_messages", 1<<0, "Send Messages", "Send messages in channels", true)
	PermManageChannels       = Register("manage_channels", 1<<1, "Manage Channels", "Create, edit, and delete channels", false)
	PermManageRoles          = Register("manage_roles", 1<<2, "Manage Roles", "Create, edit, delete roles and assign them to members", false)
	PermManageMessages       = Register("manage_messages", 1<<3, "Manage Messages", "Delete any user's messages", true)
	PermAdministrator        = Register("administrator", 1<<4, "Administrator", "Full access — bypasses all permission checks", false)
	PermMentionEveryone      = Register("mention_everyone", 1<<5, "Mention Everyone", "Use @everyone, @here, and all roles to notify users", true)
	PermViewChannels         = Register("view_channels", 1<<6, "View Channels", "View a channel and read its messages", true)
	PermAttachFiles          = Register("attach_files", 1<<7, "Attach Files", "Upload file attachments to messages", true)
	PermBanMembers           = Register("ban_members", 1<<8, "Ban Members", "Permanently ban members from the server", false)
	PermUseSlashCommands     = Register("use_slash_commands", 1<<9, "Use Slash Commands", "Use slash commands in channels", true)
	PermManageGuild          = Register("manage_guild", 1<<10, "Manage Server", "Edit server name, icon, region, and overview settings", false)
	PermKickMembers          = Register("kick_members", 1<<11, "Kick Members", "Remove members from the server (they can rejoin via invite)", false)
	PermEmbedLinks           = Register("embed_links", 1<<12, "Embed Links", "Posted links auto-expand into rich embeds", true)
	PermAddReactions         = Register("add_reactions", 1<<13, "Add Reactions", "Add new reactions to messages", true)
	PermCreatePublicThreads  = Register("create_public_threads", 1<<14, "Create Public Threads", "Create threads visible to anyone with channel access", true)
	PermCreatePrivateThreads = Register("create_private_threads", 1<<15, "Create Private Threads", "Create threads only invited members can see", true)
	PermSendInThreads        = Register("send_in_threads", 1<<16, "Send Messages in Threads", "Send messages inside threads", true)
	PermManageWebhooks       = Register("manage_webhooks", 1<<17, "Manage Webhooks", "Create, edit, and delete webhooks for channels", true)
	PermViewAuditLog         = Register("view_audit_log", 1<<18, "View Audit Log", "View the audit log of moderation and configuration actions", false)
	PermManageVanity         = Register("manage_vanity", 1<<19, "Manage Vanity URL", "Set, change, and remove the server's vanity URL", false)	
)
